name: TTSSE
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.40
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - eigen=3.4.0
  - gcc=10.4.0
  - gcc_impl_linux-64=10.4.0
  - gmp=6.2.1
  - gxx=10.4.0
  - gxx_impl_linux-64=10.4.0
  - icu=72.1
  - kernel-headers_linux-64=2.6.32
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-devel_linux-64=10.4.0
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libhwloc=2.9.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libsanitizer=10.4.0
  - libsqlite=3.42.0
  - libstdcxx-devel_linux-64=10.4.0
  - libstdcxx-ng=13.1.0
  - libuuid=2.38.1
  - libxml2=2.11.5
  - libzlib=1.2.13
  - metis=5.1.1
  - mpfr=4.2.0
  - ncurses=6.4
  - openssl=3.1.2
  - pip=23.2.1
  - pybind11=2.11.1
  - pybind11-global=2.11.1
  - python=3.10.12
  - python_abi=3.10
  - readline=8.2
  - rocm-smi=5.6.0
  - setuptools=68.0.0
  - suitesparse=5.10.1
  - sysroot_linux-64=2.12
  - tbb=2021.10.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.1
  - xz=5.2.6
