name: TTSSE
channels:
  - conda-forge
  - defaults
dependencies:
  - gcc = 15.2
  - gxx = 15.2
  - eigen = 3.4.0
  - make = 4.4.1
  - cmake = 4.2.2
  - pybind11=3.0.1
  - python = 3.9
  - suitesparse = 7.10
  - numpy = 1.26
  - scipy = 1.10